title: Notre-Dame de Paris
baseURL: https://eeibrahim-blogdown.netlify.app/
languageCode: en-us
theme: "gohugo-theme-ananke"
resourceDir: ../resources
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: yes
languages:
  en:
    contentDir: content/en
    title: My Portfolio
    weight: 1
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
params:
  author: ''
  background_color_class: bg-black
  description: 
  facebook: ''
  favicon: ''
  featured_image: /images/gohugo-default-sample-hero-image.jpg
  github: 'https://github.com/eeibrahim'
  gitlab: ''
  instagram: ''
  linkedin: ''
  mastodon: ''
  recent_posts_number: 2
  rss: ''
  site_logo: ''
  slack: ''
  stackoverflow: ''
  #twitter: https://twitter.com/GoHugoIO
  youtube: ''
